version: '3.8'

services:
  # WAHA WhatsApp HTTP API
  waha:
    image: devlikeapro/waha
    container_name: waha-whatsapp
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .waha.env
    environment:
      # WAHA Configuration
      - WAHA_API_KEY=berhasil123
      - WAHA_ENGINE=GOOGLE
      - WAHA_SESSIONS_PATH=/app/sessions
      - WAHA_MEDIA_PATH=/app/media
      - WAHA_LOG_LEVEL=INFO

      # Google Engine Configuration
      - WHATSAPP_DEFAULT_ENGINE=GOOGLE

      # Telegram Engine (backup option)
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:-}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:-}

      # Security
      - CORS_ALLOWED_ORIGINS=*

      # Database (optional, for session persistence)
      - WAHA_DB_URL=sqlite:///./app/waha.db

      # Webhooks (optional)
      - WAHA_WEBHOOK_URL=${WAHA_WEBHOOK_URL:-}

    volumes:
      # Persist sessions and media
      - waha_sessions:/app/sessions
      - waha_media:/app/media
      - waha_data:/app/data

    networks:
      - waha-network

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: waha-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - waha-network
    command: redis-server --appendonly yes

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: waha-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - waha
    networks:
      - waha-network

volumes:
  waha_sessions:
    driver: local
  waha_media:
    driver: local
  waha_data:
    driver: local
  redis_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  waha-network:
    driver: bridge